/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thetechcompanyapplication;


import java.sql.ResultSetMetaData;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CNN COMPUTERS
 */
public class addEmployee extends javax.swing.JFrame {
    private String selectedDepartment;
public void setDepartment(String department) {
        selectedDepartment = department;
        // Assuming you have a JComboBox named empdepartment
        empdepartment.addItem(department);
    }
public String getSelectedDepartment() {
        return selectedDepartment;
    }
    /**
     * Creates new form addEmployee
     */
    public addEmployee() {
        initComponents();
        Connect();
        employeetable();
        fillcombodes();
        fillcombodep();
    }
    
    
      Connection con;
    java.sql.PreparedStatement pst;
    ResultSet rs;
    
    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/thetechcompany","root","Dushan1234");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(addhrassitant.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void fillcombodep(){
    try{
        String sql="select depname from department";
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery();
        
        while(rs.next()){
        String name=rs.getString("depname");
        empdepartment.addItem(name);
        }
    
    
    }catch(Exception e){
    JOptionPane.showMessageDialog(null,e);}
    }
    public void fillcombodes(){
    try{
        String sql="select designame from designation";
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery();
        
        while(rs.next()){
        String name=rs.getString("designame");
        empdesignation.addItem(name);
        }
    
    
    }catch(Exception e){
    JOptionPane.showMessageDialog(null,e);}
    }

    
    public void employeetable(){
    
        try {
            pst=con.prepareStatement("select * from employee");
             rs=pst.executeQuery();
    ResultSetMetaData Rsm=rs.getMetaData();
    int c;
    c=Rsm.getColumnCount();
    DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
     df.setRowCount(0);
     
     while(rs.next()){
     Vector v2=new Vector();
     for(int i=1;i<=c;i++){
     v2.add(rs.getString("empno"));
     v2.add(rs.getString("empname"));
     v2.add(rs.getString("empphone"));
     v2.add(rs.getString("dob"));
     v2.add(rs.getString("adress"));
     v2.add(rs.getString("department"));
     v2.add(rs.getString("designation"));
     }
     df.addRow(v2);
     }
        } catch (SQLException ex) {
            Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empnumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        empname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        empphone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        empdob = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empadress = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        empdesignation = new javax.swing.JComboBox<>();
        deletebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        ubdatebtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        exitbtn = new javax.swing.JButton();
        empdepartment = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD EMPLOYEE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 317, 32));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EPF NO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 50, 79, 26));
        jPanel1.add(empnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 51, 200, 26));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 95, 79, 26));
        jPanel1.add(empname, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 96, 200, 26));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 140, 79, 26));

        empphone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(empphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 141, 200, 26));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Birth");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 185, -1, 26));

        empdob.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(empdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 185, 200, 26));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 229, 79, 28));

        empadress.setColumns(20);
        empadress.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        empadress.setRows(5);
        empadress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(empadress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 200, 39));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Department");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 95, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Designation");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 95, -1));

        empdesignation.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        empdesignation.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(empdesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 210, 26));

        deletebtn.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel1.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 400, 84, 31));

        addbtn.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 400, 84, 31));

        ubdatebtn.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        ubdatebtn.setText("UPDATE");
        ubdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubdatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(ubdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, 31));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("EMPLOYEE DETAILS");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 6, 723, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EPF NO", "NAME", "PHONE NO", "DATE OF BIRTH", "ADDRESS", "DEPARTMENT", "DESIGNATION"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 50, 691, 376));

        exitbtn.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        exitbtn.setText("EXIT");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 400, 90, 31));

        empdepartment.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        empdepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empdepartmentActionPerformed(evt);
            }
        });
        jPanel1.add(empdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1070, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thetechcompanyapplication/fixabe 1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        pack();
    }// </editor-fold>                        

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        String empno=empnumber.getText();
        String username=empname.getText();
        String phoneno=empphone.getText();
        String empdo=empdob.getDateFormatString();
        String address=empadress.getText();
        String department=empdepartment.getSelectedItem().toString();
        String designation=empdesignation.getSelectedItem().toString();
        
        
        try {
            pst=con.prepareStatement("insert into employee(empno,empname,empphone,dob,adress,department,designation)values(?,?,?,?,?,?,?)");
            
            pst.setString(1,empno);
            pst.setString(2, username);
            pst.setString(3, phoneno);
            pst.setString(4,((JTextField)empdob.getDateEditor().getUiComponent()).getText());
             pst.setString(5,address);
              pst.setString(6,department);
               pst.setString(7,designation);
            pst.executeUpdate();
             JOptionPane.showMessageDialog(this,"Employee Succesfully Inserted"); 
             
             empnumber.setText("");
             
       empname.setText("");
        empphone.setText("");
        empdob.setDateFormatString("");
        empadress.setText("");
        employeetable();
     
        } catch (SQLException ex) {
            Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(this,"Error,Try again");
        }
           
            
           
    }                                      

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String empno = empnumber.getText();

    try {
        pst = con.prepareStatement("DELETE FROM employee WHERE empno = ?");
        pst.setString(1, empno);
        int result = pst.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Employee deleted successfully");
        } else {
            JOptionPane.showMessageDialog(this, "Employee not found or could not be deleted");
        }

        // Clear the text fields and update the table
        empnumber.setText("");
        empname.setText("");
        empphone.setText("");
        empdob.setDateFormatString("");
        empadress.setText("");
        employeetable();
        addbtn.setEnabled(true);

    } catch (SQLException ex) {
        Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error, Try again");
    }
    }                                         

    private void ubdatebtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
         String empno = empnumber.getText();
    String username = empname.getText();
    String phoneno = empphone.getText();

    // Get the selected date from JDateChooser
    java.util.Date dateOfBirth = empdob.getDate();

    // Check if a date is selected
    if (dateOfBirth != null) {
        String address = empadress.getText();
        String department = empdepartment.getSelectedItem().toString();
        String designation = empdesignation.getSelectedItem().toString();

        try {
            // Use SimpleDateFormat to format the date
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDateOfBirth = dateFormat.format(dateOfBirth);

            pst = con.prepareStatement("update employee set empname=?, empphone=?, dob=?, adress=?, department=?, designation=? where empno=?");
            pst.setString(1, username);
            pst.setString(2, phoneno);
            pst.setString(3, formattedDateOfBirth);
            pst.setString(4, address);
            pst.setString(5, department);
            pst.setString(6, designation);
            pst.setString(7, empno);

            int updateResult = pst.executeUpdate();

            if (updateResult > 0) {
                JOptionPane.showMessageDialog(this, "Employee details updated successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update employee details");
            }

            // Clear the text fields and update the table
            empnumber.setText("");
            empname.setText("");
            empphone.setText("");
            empdob.setDate(null); // Clear the date
            empadress.setText("");
            employeetable();
            addbtn.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error, Try again");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a valid date of birth");
    }
    }                                         

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        Homepage h=new Homepage();
        h.setVisible(true);
        this.dispose();
    }                                       

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
       DefaultTableModel d1 = (DefaultTableModel) jTable1.getModel();
    int selectIndex = jTable1.getSelectedRow();
    empnumber.setText(d1.getValueAt(selectIndex, 0).toString());
    empname.setText(d1.getValueAt(selectIndex, 1).toString());
    empphone.setText(d1.getValueAt(selectIndex, 2).toString());

    String dateStr = d1.getValueAt(selectIndex, 3).toString();
    Date date = null;
    try {
        date = new SimpleDateFormat("yyyy-MM-dd").parse(dateStr);
    } catch (ParseException ex) {
        Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, ex);
    }
    empdob.setDate(date);

    // Fix here: Change empname.setText to empadress.setText
    empadress.setText(d1.getValueAt(selectIndex, 4).toString());

    empdepartment.setSelectedItem(d1.getValueAt(selectIndex, 5).toString());
    empdesignation.setSelectedItem(d1.getValueAt(selectIndex, 6).toString());
    addbtn.setEnabled(false);

       
    }                                    

    private void empdepartmentActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         
        java.awt.EventQueue.invokeLater(() -> {
            new addEmployee().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextArea empadress;
    private javax.swing.JComboBox<String> empdepartment;
    private javax.swing.JComboBox<String> empdesignation;
    private com.toedter.calendar.JDateChooser empdob;
    private javax.swing.JTextField empname;
    private javax.swing.JTextField empnumber;
    private javax.swing.JFormattedTextField empphone;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton ubdatebtn;
    // End of variables declaration                   
}
